### ISSUE TITLE
Feature Enhancement - Agregatte Parameters Scanned

### ISSUE THREAD

**Issue by AkikoOrenji** [pentagridsec/PentagridScanController#3]
Hi,

Just watched your talk from earlier in the year and i have been dealing with Portswigger support on similar issues.  Controller looks like a great answer to some of my issues. 
While Controller will reduce duplication at the request level Burps selection of injection points is still a bug bear for optimal scanning.  While there are definitely advantages in scanning the same headers and parameters on different requests it would be good if there was a way to report on and de-duplicate at the injection point level. Just some report of what was being scanner  would help identify injection points missed by the default scanner so they can be manually added and scanned. 
From your experience with Controller how feasible would it be to collate and report on the injection points being scanned and optimize those injection points into the scanner  ? 

I ask as i find myself constantly using  'manually send to scanner'  due to the large number of parameters and requests involved in complex applications.  For an initial scan it isn't a good use of time to be scanning headers and cookies over and over again in different requests. I've had tickets open with Portswigger as their de-duplication doesn't appear to work as per the documentation. i've been thinking of writing a tool to do this myself and it seems like Controller might be the correct place for this capability also. 

![image](https://user-images.githubusercontent.com/30274508/197700428-d8f70c48-574a-498b-8e5a-d4d6d4f4a522.png)

**Comment by floyd-fuh** [comment]
Hi there,

Thanks for your interest. The entire topic is not that easy to handle and can be quite complex. Here's a couple of thoughts:

1. Deduplication of injection points is not deterministic. Just because a parameter has the same name it doesn't mean it is handled the same on the server side. Also, keep in mind that some parameters don't have any "good" identifiers, for example the third item in a JSON list (doesn't have a name). It wouldn't make sense to only scan the third item in a JSON list once and then never again, maybe it's something completely different later.
2. So far we are limited by the Burp API. You can't configure active scanning from an extension with the old API. You can just say "scan this request", nothing else. But the new API that is brand new can apparently: https://github.com/PortSwigger/burp-extensions-montoya-api/blob/main/src/main/java/burp/api/montoya/scanner/Scan.java
3. What you could do is tell the user to change the insertion points of the "Extension driven active audit" item in the dashboard to uncheck all "Insertion Point Types" and then provide your own insertion points from the extension. But with the new API it seems you can do that as well.

Summary: I think the extension should be changed to support the brand new montoya API.

I'm currently working on the extension (with the old API) and will push the updates soon. Then it would probably be time to port the entire extension to the new API.

But for now: Go ahead and write your own extension with the Montoya API, I would be really interested to see it. My advice: Use Kotlin! I even had to learn Kotlin just to write Burp extension in it, but it saves you so much trouble later. I'm super happy with Kotlin in this extension... the only problem being that Portswigger are using Java themselves. So you need to create an equivalent of https://github.com/bao7uo/burp-extender-api-kotlin but for Montoya API first. And the problem is Burp won't really tell you which objects can be null (or not) so you just have to guess... But it's feasible. Have fun!

**Comment by floyd-fuh** [comment]
There is progress in regards to the Montoya API but I don't think this feature is going to make it into the Scan Controller any time soon

**Comment by AkikoOrenji** [comment]
Thanks for your thoughts.
